# Etapa base: runtime de ASP.NET
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# Etapa build: SDK para compilar
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar primero los csproj para aprovechar la caché de restore
COPY ./src/Common/Common.csproj ./Common/
COPY ./src/Contracts/Contracts.csproj ./Contracts/
COPY ./src/MonitorApi/MonitorApi.csproj ./MonitorApi/
RUN dotnet restore ./MonitorApi/MonitorApi.csproj

# Copiar el resto del código
COPY ./src/Common ./Common
COPY ./src/Contracts ./Contracts
COPY ./src/MonitorApi ./MonitorApi
WORKDIR /src/MonitorApi
RUN dotnet publish -c Release -o /app/publish

EXPOSE 5100

# Etapa final: runtime ASP.NET
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MonitorApi.dll"]
